SQLAlchemy's Metadata object(:py:attr:`ckan.model.meta.metadata`) is no longer
bound the the DB engine. [A number of
operations](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed),
such as `table.exists()`, `table.create()`, `metadata.create_all()`,
`metadata.reflect()`, now produce an error
:py:class:`sqlalchemy.exc.UnboundExecutionError`.

Depending on the situation, following changes may be required:

* Instead of creating tables via custom CLI command or during application
  startup, use [Alembic
  migrations](https://docs.ckan.org/en/2.10/extensions/best-practices.html#use-migrations-when-introducing-new-models)

* If there is no other way, change `table.create()`/`table.exists()` to
  `table.create(engine)`/`table.exists()`. Get `engine` by calling
  :py:func:`~ckan.model.ensure_engine`.
